### ISSUE TITLE
N-point scan's location in the dashboard interface

### ISSUE THREAD

**Issue by sstoneb** [MITHaystack/srt-py#10]
Currently, the way to perform an N-point scan is to click the object of interest on the star chart and select "n-point scan" from a dialog box. If the user wants to save their scan data, they have to begin recording beforehand.

Speaking only for myself, N-point scan "feels" like a routine that should be located under the routine menu because the telescope performs a sequence of pre-programmed actions. If placed on this menu, the SRT could perform the scan with the current location of the SRT as its center point. This would also allow scans to be done of objects that aren't already marked on the star chart. I'd further suggest that when an N-point scan is started this way a reminder of some sort should show up that the user must start recording first if they want to keep the data.

If this change were made, N-Point scan could probably be removed from the pointing dialog that comes up when clicking objects on the star chart. If the "beam switch" choice (whatever that is!) gets removed too, the pointing dialog could be changed to a simple confirmation: "Point to <object>?"

**Comment by jswoboda** [comment]
Added in commit 39b268f14246a897a308adb0520ea951af344b9c. Was tested and see below.

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/2608303/182695357-a920adad-ff04-4fca-9d43-9d06f25fb9c5.png">
